on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Show the branch and PR details which get merged to main
        run: echo "This workflow was triggered by a pull request to the ${{ github.base_ref }} branch. The PR number is ${{ github.event.pull_request.number }} and the title is '${{ github.event.pull_request.title }}'."
      
      - name: print
        run: echo "the gate keeper checks are completed"